### ISSUE TITLE
Cannot create playlists whose content is based on search criteria

### ISSUE THREAD

**Issue by tsirysndr** [tsirysndr/music-player#130]
Out of curiosity, are smart playlists (playlists whose content is based on search criteria, rather than static lists) something that might be in scope for this project?

_Originally posted by @ErichDonGubler in https://github.com/tsirysndr/music-player/issues/76#issuecomment-1397060842_

**Comment by ErichDonGubler** [comment]
Funnily enough, I think that I intended my original question one way (a feature request), and it got interpreted as another (a valid bug report for a different behavior). Let me see if I can clarify what I meant.

When I say "smart playlist", I mean a playlist whose content is dynamically populated. You can think of it as a saved search that has a name, which can be turned into a play queue just like other playlists. For instance, in Rocket Player for Android, or iTunes, one can create a playlist with rules that query fields (i.e., "all songs with 5 stars").

Does that help?

**Comment by tsirysndr** [comment]
Ok, I understand now, I will look at how we can add this feature
