### ISSUE TITLE
Windows desktop file ".msi" cannot be reached

### ISSUE THREAD

**Issue by la-fourier** [tsirysndr/music-player#152]
Clicking on the download button for windows desktop version of music-player leads to a 404-Page.

**Comment by tsirysndr** [comment]
currently there is a build problem for windows because of the `openssl-sys` package

**Comment by la-fourier** [comment]
Oh lol having a build problem bc/o that in another project too so I will know when it resolved itself but didn´t know that u use it, thanks!
