### ISSUE TITLE
ci:  add x86_64-pc-windows-gnu build

### ISSUE THREAD

**Issue by tsirysndr** [tsirysndr/music-player#26]

**Comment by ahmedsilat44** [comment]
@tsirysndr Do you have any resources where I can learn to do this.

**Comment by tsirysndr** [comment]
@ahmedsilat44 thanks for your interest in the project, yes I have already started a bit : I added a github action [workflow](https://github.com/tsirysndr/music-player/blob/master/.github/workflows/release-for-windows.yml) but it's not finished yet, I need to add a softprops/action-gh-release@v1 step like on the other workflows, you can continue on that if you want
