### ISSUE TITLE
create a discord chat for all discussions about the project and add the badge to the README.md

### ISSUE THREAD

**Issue by tsirysndr** [tsirysndr/music-player#31]

**Comment by blitty-codes** [comment]
Hello, I can create the discord server with a discord chat for discussions. Once the issue is solved, I give you the ownership.

**Comment by tsirysndr** [comment]
Thanks, I assigned you the issue, you can add a [badge](https://github.com/ashmonty/discord-md-badge)  to the README.md and create a PR

**Comment by blitty-codes** [comment]
Done. Pull request #33
